"""empty message

Revision ID: 0e5708946f68
Revises: 61392e0900f1
Create Date: 2018-03-12 17:40:06.739257

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0e5708946f68'
down_revision = '61392e0900f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('common_user', 'realname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('common_user', sa.Column('realname', mysql.VARCHAR(length=64), nullable=True))
    # ### end Alembic commands ###
