"""empty message

Revision ID: 1872e13508ca
Revises: 30f72ad327ec
Create Date: 2018-02-06 11:12:33.707295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1872e13508ca'
down_revision = '30f72ad327ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher', sa.Column('gender', sa.String(length=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teacher', 'gender')
    # ### end Alembic commands ###
