"""empty message

Revision ID: 1d9cdcb36ea4
Revises: e6bae1c8465d
Create Date: 2018-03-13 00:06:05.862922

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1d9cdcb36ea4'
down_revision = 'e6bae1c8465d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('common_user', '_password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('common_user', sa.Column('_password', mysql.VARCHAR(length=255), nullable=False))
    # ### end Alembic commands ###
