"""empty message

Revision ID: 62ede1fea4af
Revises: 4dbbbce22943
Create Date: 2018-02-07 16:22:01.153411

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '62ede1fea4af'
down_revision = '4dbbbce22943'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teacher', 'hiredate',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teacher', 'hiredate',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
