"""empty message

Revision ID: 753ac22d74cf
Revises: 1d9cdcb36ea4
Create Date: 2018-03-13 00:10:34.354118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '753ac22d74cf'
down_revision = '1d9cdcb36ea4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('common_user', sa.Column('_password', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('common_user', '_password')
    # ### end Alembic commands ###
