"""empty message

Revision ID: 7f386e636e22
Revises: 1872e13508ca
Create Date: 2018-02-06 14:45:47.652651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f386e636e22'
down_revision = '1872e13508ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher', sa.Column('hiredate', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teacher', 'hiredate')
    # ### end Alembic commands ###
