"""empty message

Revision ID: 7f7fbb98bd37
Revises: ea5835407d3d
Create Date: 2018-02-07 10:24:30.199277

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7f7fbb98bd37'
down_revision = 'ea5835407d3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teacher', 'salary')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher', sa.Column('salary', mysql.VARCHAR(length=20), nullable=True))
    # ### end Alembic commands ###
