"""empty message

Revision ID: 9f05230d8413
Revises: 99922e432b9b
Create Date: 2018-02-22 15:37:13.427302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f05230d8413'
down_revision = '99922e432b9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('common_user', sa.Column('email', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'common_user', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'common_user', type_='unique')
    op.drop_column('common_user', 'email')
    # ### end Alembic commands ###
