"""empty message

Revision ID: aac6e241f774
Revises: adee69713154
Create Date: 2018-02-22 15:48:58.234815

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aac6e241f774'
down_revision = 'adee69713154'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('common_user', sa.Column('username', sa.String(length=64), nullable=False))
    op.drop_column('common_user', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('common_user', sa.Column('name', mysql.VARCHAR(length=64), nullable=False))
    op.drop_column('common_user', 'username')
    # ### end Alembic commands ###
