"""empty message

Revision ID: adee69713154
Revises: 58a302280d3f
Create Date: 2018-02-22 15:43:09.327717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adee69713154'
down_revision = '58a302280d3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('common_user', sa.Column('gender', sa.String(length=1), server_default='男', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('common_user', 'gender')
    # ### end Alembic commands ###
