"""empty message

Revision ID: b2399542cb2d
Revises: 
Create Date: 2018-02-11 18:03:27.878864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2399542cb2d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('common_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('common_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('phone', sa.String(length=11), nullable=False),
    sa.Column('gender', sa.String(length=1), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('common_role_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('common_user_id', sa.Integer(), nullable=True),
    sa.Column('common_role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['common_role_id'], ['common_role.id'], ),
    sa.ForeignKeyConstraint(['common_user_id'], ['common_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('common_role_user')
    op.drop_table('common_user')
    op.drop_table('common_role')
    # ### end Alembic commands ###
