"""empty message

Revision ID: d78be4a62a1f
Revises: e88e0b307a56
Create Date: 2018-02-22 15:40:55.672893

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd78be4a62a1f'
down_revision = 'e88e0b307a56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('common_user', 'gender')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('common_user', sa.Column('gender', mysql.VARCHAR(length=1), server_default=sa.text("'男'"), nullable=False))
    # ### end Alembic commands ###
