"""empty message

Revision ID: d872bfc12201
Revises: 753ac22d74cf
Create Date: 2018-03-17 23:51:30.563410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd872bfc12201'
down_revision = '753ac22d74cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apitest_project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=255), nullable=True),
    sa.Column('project_description', sa.String(length=255), nullable=True),
    sa.Column('module_count', sa.Integer(), nullable=True),
    sa.Column('interface_count', sa.Integer(), nullable=True),
    sa.Column('create_date', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('modify_date', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['common_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('apitest_module',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_name', sa.String(length=255), nullable=True),
    sa.Column('module_description', sa.String(length=255), nullable=True),
    sa.Column('create_date', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('modify_date', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['apitest_project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['common_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('apitest_interface',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interface_name', sa.String(length=255), nullable=True),
    sa.Column('interface_url', sa.String(length=255), nullable=True),
    sa.Column('interface_headers', sa.String(length=255), nullable=True),
    sa.Column('interface_method', sa.String(length=255), server_default='GET', nullable=True),
    sa.Column('interface_params', sa.String(length=255), nullable=True),
    sa.Column('interface_response', sa.String(length=255), nullable=True),
    sa.Column('interface_description', sa.String(length=255), nullable=True),
    sa.Column('create_date', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('modify_date', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('developer_id', sa.Integer(), nullable=True),
    sa.Column('tester_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('module_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['developer_id'], ['common_user.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['apitest_module.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['common_user.id'], ),
    sa.ForeignKeyConstraint(['tester_id'], ['common_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('apitest_interface_case',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interface_url', sa.String(length=255), nullable=True),
    sa.Column('interface_headers', sa.String(length=255), nullable=True),
    sa.Column('interface_method', sa.String(length=255), server_default='GET', nullable=True),
    sa.Column('interface_params', sa.String(length=255), nullable=True),
    sa.Column('interface_response', sa.String(length=255), nullable=True),
    sa.Column('interface_response_assert', sa.String(length=255), nullable=True),
    sa.Column('create_date', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('modify_date', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('interface_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['interface_id'], ['apitest_interface.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['common_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('apitest_caseresult',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interface_case_id', sa.INTEGER(), nullable=True),
    sa.Column('create_date', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('result', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['interface_case_id'], ['apitest_interface_case.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['common_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apitest_caseresult')
    op.drop_table('apitest_interface_case')
    op.drop_table('apitest_interface')
    op.drop_table('apitest_module')
    op.drop_table('apitest_project')
    # ### end Alembic commands ###
