"""empty message

Revision ID: d9966b97755a
Revises: 7f7fbb98bd37
Create Date: 2018-02-07 10:25:17.142532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9966b97755a'
down_revision = '7f7fbb98bd37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher', sa.Column('salary', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teacher', 'salary')
    # ### end Alembic commands ###
