"""empty message

Revision ID: e6bae1c8465d
Revises: b3884a51f25a
Create Date: 2018-03-13 00:03:39.012082

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e6bae1c8465d'
down_revision = 'b3884a51f25a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('common_user', sa.Column('_password', sa.String(length=255), nullable=False))
    op.drop_column('common_user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('common_user', sa.Column('password', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('common_user', '_password')
    # ### end Alembic commands ###
