"""empty message

Revision ID: ea5835407d3d
Revises: 7f386e636e22
Create Date: 2018-02-06 18:56:59.862704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea5835407d3d'
down_revision = '7f386e636e22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher', sa.Column('salary', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teacher', 'salary')
    # ### end Alembic commands ###
